[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
nixLibs = ["glibc"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["cd frontend && bun run build"]

[start]
# Frontend is static, so we need a simple file server
cmd = "echo 'Frontend built successfully. Serve the dist folder with a static file server.'"

