[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
nixLibs = ["glibc"]

[phases.install]
# Install all dependencies including devDependencies for building
cmds = ["cd /app && bun install --frozen-lockfile --production=false"]

[phases.build]
cmds = ["cd frontend && NODE_ENV=production bun run build"]

[start]
# Railway-compatible static server
cmd = "bun frontend/railway-static.js"

# Railway rebuild trigger: 1761251371
# Force rebuild Thu Oct 23 16:32:04 EDT 2025
