[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
nixLibs = ["glibc"]

[phases.install]
# Install from monorepo root to access workspace dependencies
cmds = ["cd .. && bun install --frozen-lockfile && cd frontend"]

[phases.build]
cmds = ["bun run build"]

[start]
# Frontend is static, so we need a simple file server
# Railway will serve the dist folder
cmd = "echo 'Frontend built successfully. Serve the dist folder with a static file server.'"

