[phases.setup]
nixPkgs = ['bun'] # Bun’s the boss

[phases.build]
cmds = ['bun install', 'bun run build'] # Build that Vite goodness

[start]
cmd = 'bunx serve dist -s' # Serve it up, SPA-style

[staticAssets]
mountPath = '/'
destination = '/app/dist'