[build]
# Install dependencies from monorepo root
install = """
curl -fsSL https://bun.sh/install | bash
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
bun install
"""
# Custom build step
build = "cd frontend && bun run build"

[dev]
# How to start your application
cmd = "cd frontend && bun run dev"
