[build]
# Replace Railway's automatic npm install phase
install = """
curl -fsSL https://bun.sh/install | bash
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
bun install
"""
# Custom build step
build = "bun run build"

[dev]
# How to start your application
cmd = "bun run dev"
