[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
nixLibs = ["glibc"]

[phases.install]
# Install from monorepo root to access workspace dependencies
cmds = ["cd .. && bun install --frozen-lockfile && cd backend"]

[start]
cmd = "bun server.js"
