[build]
# Install dependencies from monorepo root to access shared workspace
install = """
curl -fsSL https://bun.sh/install | bash
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
cd .. && bun install && cd backend
"""

[dev]
# How to start your app
cmd = "bun run dev"
